### ISSUE TITLE
Move help.datahub.io to the forum

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#389] opened 2015-12-01 10:40 UTC
* [x] Create DataHub category under labs
* [x] Create a a topic in that category replicating existing instructions
* [x] Implement redirect from current links in datahub.io to that topic
* [x] move over any relevant content (e.g. KB articles) - if needed

Bonus points:

* deprecate blog.datahub.io and move posts to okfnlabs.org and implement redirect

**Comment by danfowler** [comment] 2015-12-02 07:35
Topic created: https://discuss.okfn.org/t/creating-a-dataset-on-the-datahub/1627

@amercader can you assist with the final step in somehow linking "help" on datahub.io to https://discuss.okfn.org/c/open-knowledge-labs/datahub

**Comment by rgrp** [comment] 2015-12-02 08:28
@danfowler I'm suggesting we do a redirect of help which would mean this would not be required to mess with datahub.io - it can just keep linking and we do the redirect.

**Comment by rgrp** [comment] 2015-12-02 08:29
@danfowler this could have been a good one for another member of labs - do we have any folks you can start @-ing in these issues and inviting to participate - they can always say they are busy so i think no imposition to invite.

**Comment by danfowler** [comment] 2015-12-02 08:59
@rgrp yeah, I realized that after I started :/.  Will definitely start doing this.

**Comment by amercader** [comment] 2015-12-02 09:18
@danfowler let me know if you need to do something on the datahub side

**Comment by danfowler** [comment] 2015-12-04 10:57
@amercader thanks. I think all you should do for now is watch [that topic](https://discuss.okfn.org/c/open-knowledge-labs/datahub/) on discuss.okfn.org.  Are you OK receiving support requests there?

**Comment by rgrp** [comment] 2015-12-04 11:26
@danfowler to be clear we would *really* like to get to a place where it is not @amercader who is creating organizations etc for people i.e. we really want to find another datahub admin (even you for the present) who can do what is necessary (which would mean that @amercader would not need to watch stuff ;-) ...)

**Comment by danfowler** [comment] 2015-12-04 11:26
@rgrp totally understood :)

**Comment by amercader** [comment] 2015-12-04 11:31
Just to be clear I haven't been personally creating orgs on Datahub for a while now, as I assumed that was done by somebody else (maybe you @danfowler?). I only acted on the actual issues reported like failing uploads, API problems, etc, most caused by the migration to cloud.
I'm monitoring the discourse thread and will keep an eye on major issue like the ones mentioned but I'm afraid I don't have time for acting on the org creation requests.

**Comment by danfowler** [comment] 2015-12-04 11:51
@amercader I have been creating orgs, I meant for the actual issues :)

**Comment by amercader** [comment] 2015-12-04 12:37
@danfowler you are the man :sunglasses: cheers

**Comment by rgrp** [comment] 2015-12-15 12:58
@danfowler any update here? It would be good to close this out - perhaps at this point just best if you do it and take care of redirects (I can tell you how or do this myself).

**Comment by danfowler** [comment] 2015-12-16 13:24
@rgrp I can close this out. Is there a way to access the Tender site after help.datahub.io redirects to discuss?

**Comment by rgrp** [comment] 2015-12-17 22:36
@danfowler surely you do the redirects in our DNS system ;-) As suggested can you ping me quickly and i brief you on how to do this.

**Comment by rgrp** [comment] 2016-01-08 11:43
@danfowler I would also suggest we also shut down blog.datahub.io - moving any relevant content to forum with notice about source and original date. e.g. http://blog.datahub.io/2013/10/11/organization-migration-complete/. We also need to implement the redirect from http://blog.datahub.io/2013/10/11/organization-migration-complete/ and http://blog.datahub.io generally to the new forum post about registering an organization ;-)

**Comment by todrobbins** [comment] 2016-01-08 18:39
@rgrp would a shut down also include removing the blog as well or just migrating a copy of the blog content to the forum?

**Comment by danfowler** [comment] 2016-01-13 18:52
Closing as help.datahub.io has been redirected (and we have a few requests coming in already).  Creating new issue for blog.datahub.io.

**Closed by danfowler** 2016-01-13 18:52 UTC

**Comment by danfowler** [comment] 2016-01-14 13:46
@todrobbins I would think we would shut down the blog and in the future post announcements about the service to the discussion forum.
