### ISSUE TITLE
New Badges Round 2

### ISSUE THREAD

**Issue by danfowler** [okfn/okfn.github.com#354] opened 2015-06-30 09:44 UTC
Next steps following up on https://github.com/okfn/okfn.github.com/issues/278
- remove potentially redundant roles ("webmin")?
- thinking about workflow/interface for issuing/requesting a badge?
- think about what might make people want to earn a badge?
- integrating with discuss.okfn.org?
- New Badges: 
  - Data Curator
  - Managing Data Curator badges

**Comment by rgrp** [comment] 2015-06-30 09:45
Also additional badges like:

Data Curator and Managing Data Curator badges

**Comment by rgrp** [comment] 2016-04-10 13:03
WONTFIX / DUPLICATE of https://discuss.okfn.org/t/nicer-badge-icons-images/2108

Rather than fix here should make this part of badging effort on the main OK directory.

**Closed by rgrp** 2016-04-10 13:03 UTC
